"""empty message

Revision ID: 2def32aa7a55
Revises: None
Create Date: 2014-11-10 13:44:28.516273

"""

# revision identifiers, used by Alembic.
revision = '2def32aa7a55'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
